### ISSUE TITLE
payflow adjustments

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#46]
The Payflow needs some work, I noticed this when performing QA on paypal and credit cards
TASKS to complete:
**### TASK 1**
- [x] When entering credit cards, expiration date fields and cvv fields highlight in red, when there is no issue at all, please fix this bug
![false-error-alert](https://user-images.githubusercontent.com/10249755/47440308-e3f16f00-d77b-11e8-8537-caf0cb34fbff.png)

**### TASK 2**
- [x] checkout confirmation page is to plain and should be more useful: After payment was made, This Is what I received, this leaves  allot to be desired: Please add the following information: to confirmation page:
1. Reservation number
2. Booked travel dates
3. Message “ An email has been dispatched to your inbox (please add info@bnbfusion.com to your contacts in order to receive communications from us), containing your reservation details, you may also click [here](https://www.bnbfusion.com/user/listing/trips) to view more information on your reservation and edit your profile.
![confirmation-page](https://user-images.githubusercontent.com/10249755/47439667-ca9bf300-d77a-11e8-9e6a-70b87f3216f9.png)

**### TASK 3**
- [x] On page: https://www.bnbfusion.com/user/listing/trips
Check in /out dates are not displaying data, please fix this. I do believe this was handled in a previous issue. This is the second time I request this data to be present.
![no-dates-checkin-checkout](https://user-images.githubusercontent.com/10249755/47439889-2b2b3000-d77b-11e8-87a8-bfe060fee311.png)

**Comment by mindrootstech** [comment]
Marco,

Point 1 is resolved.
For Point 2, we have updated the Thanks you page with the provided content.

For Point 3, If you look closely, the Booking dates are specified on the left hand side in the first row.
The check in column gets filed the day the user actually checks in.
Thats how this functionality has always been working. So nothing done here.

Effort to setup the Thank you page: $30.
Please review.

**Comment by mindrootstech** [comment]
This is how the Thank you page looks now.
![screenshot 2018-10-25 at 6 29 50 pm](https://user-images.githubusercontent.com/19343942/47501801-02db2880-d884-11e8-9dc5-0cec207150b0.png)

**Comment by mnights101** [comment]
paid via upwork
