### ISSUE TITLE
Listing cover image, match Airbnb

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#52]
Please match airbnb Main image, to complete this task:
example URL: https://www.airbnb.com/rooms/22292330?location=Punta%20Cana%2C%20La%20Altagracia%20Province%2C%20Dominican%20Republic&adults=1&guests=1&toddlers=0&check_in=2019-01-30&check_out=2019-01-31

**TASKS:**

- [x] Move gallery to header and display in mosaic like airbnb

- [x] match image display sizes as displayed on airbnb

- [x] On hover images pop out a bit view URL example

- [x] On resize image count display goes from 1 main pic and 4 thumbnails to 1 main pic and 2 thumbnails and on further resize it goes to only one main picture with scroll dots overlay, on click it displays gallery

- [x] add view photos button over image lower right corner, on resize to mobile changes this disappears

- [x] add share button with same functionality/ on resize to mobile this changes to icon, match airbnb

- [x] add save button over images as displayed on mobile this turns to icon as

**Comment by mindrootstech** [comment]
Marco,

To implement this, we will have to setup the design for listing gallery in desktop and mobile views, implement share and save functionality. (I can see save icon in search but its not working).

Total effort will be $250
Please approve

**Comment by mnights101** [comment]
Manik, task 1 remains. the button does not dissapear for small screens , on resize it should turn into bullet points  to indicate there is a gallery as seen on airbnb screen resize

**Comment by mindrootstech** [comment]
Hi Marco,

The mobile screens have been updated with the bullet points for the gallery as asked for.
Please review and update.

**Comment by mnights101** [comment]
PAID via upwork milestone 20
