### ISSUE TITLE
minor changes to UI/UX

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#55]
Minor changes:

- [x] please extend character limit on title from 35 characters to 66

- [x] please extend description character limit to unlimited, however after 500 characters we will display a "Read more about the space"  as shown in screenshot. when clicked it will reveal text
![read-more-description](https://user-images.githubusercontent.com/10249755/55827079-632ef100-5ad7-11e9-9524-25d6111a8711.png)

- [x] set default currency to USD instead of current NZ

- [x] In admin property listing, please change titles to the title of listing not "entire house in Punta Cana" this makes it very hard to find particular properties
![change-listing-title](https://user-images.githubusercontent.com/10249755/55829151-fec26080-5adb-11e9-83e8-6b7a087fd5fa.png)

- [x] change UI site wide background as numbered in screenshot to all white including footer color code #ffffff, and yes this includes the black background in top of reservation box
![turn-to-white](https://user-images.githubusercontent.com/10249755/55830696-7e056380-5adf-11e9-9efa-7b23c558d5cc.png)

- [x] change property listing title color code #484848 font: circular font size 32px font weight 800

- [x] change Bold text on listing page to color code #484848 font: circular font size 16px font weight 800

https://lineto.com/The+Fonts/Font+Categories/Text+Fonts/Circular/

- [x] change normal text to color code #484848 font circular , font size 16 px, font  weight 400

- [x] change links sitewide to color code #008489 font: circular font size 16px font weight 600

- [x] change icon profile image size to 62x60px
![new icon-image-size](https://user-images.githubusercontent.com/10249755/55830923-05eb6d80-5ae0-11e9-9e16-848c2bb31998.png)

- [x] change footer text to color code #484848 font circular , font size 14 px, font  weight 600

Please quote and ETA

**Comment by mindrootstech** [comment]
Effort of $120 to get all these tasks done.
ETA of 1 working day.
Please approve.

**Comment by mnights101** [comment]
Approved, can we mirror this onto eros radar as well?

-- 
 BNBFUSION
 info@bnbfusion.com

**Comment by mindrootstech** [comment]
Sure... i'll let you know the minor extra effort for the mirror on erosradar as well.

**Comment by mnights101** [comment]
will this be mirrored on erosradar?

**Comment by mnights101** [comment]
pAID via upwork

**Comment by mindrootstech** [comment]
Have been mirrored on Erosradar as well.
Effort - $25

**Comment by mnights101** [comment]
this task remains incomplete

please extend description character limit to unlimited, however after 500 characters we will display a "Read more about the space" as shown in screenshot. when clicked it will reveal text

in listing description after 500 words in frontend it does not say Read more about the space" and it does not drop down rest of text

Please fix this

**Comment by mindrootstech** [comment]
Hi Marco,

Issue has been resolved.
Please check and verify.

**Comment by mnights101** [comment]
25 balance paid via upwork on milestone 26
